### ISSUE TITLE
Forecast accuracies diverge when first_difference = TRUE

### ISSUE THREAD

**Issue by luke-a-rogers** [pbs-assess/pbsEDM#12]
When `first_difference = TRUE`, the forecast accuracy metrics `N_rho` and `X_rho` can be wildly different (e.g. examples 2 and 3 for `pbsEDM()` and `pbsSmap()`). The current method to compute `N_forecast` is `N_forecast_{t} = N_forecast_{t-1} + D_forecast_{t-1}` where `D_forecast` is the forecast of `D_observed`, and `D_observed_{t} = N_observed_{t+1} - N_observed_{t}`.

- Check that the computation of `N_forecast` is correct
- Identify a better way to compute `N_forecast` if possible
- Think through the implications of inflated `X_rho` but deflated `N_rho` when `first_difference = TRUE`

**Comment by andrew-edwards** [comment]
So I think the errors compound with 
```N_forecast_{t} = N_forecast_{t-1} + D_forecast_{t-1}```.
So should this just be
```N_forecast_{t} = N_observed_{t-1} + D_forecast_{t-1}```?

At least for one-step-ahead forecasting Otherwise all the little errors in ```D_{1}, D_{2}, ...``` add up.

And your ```D``` could be ```Y``` yes, to match the notation?

**Comment by luke-a-rogers** [comment]
> So I think the errors compound with
> `N_forecast_{t} = N_forecast_{t-1} + D_forecast_{t-1}`.
> So should this just be
> `N_forecast_{t} = N_observed_{t-1} + D_forecast_{t-1}`?
> 
> At least for one-step-ahead forecasting Otherwise all the little errors in `D_{1}, D_{2}, ...` add up.
> 
> And your `D` could be `Y` yes, to match the notation?

Ahhh, yes to both. The `N_forecast_{t} = N_forecast_{t-1} + D_forecast_{t-1}` was a typo on my part - the code matches `N_forecast_{t} = N_observed_{t-1} + D_forecast_{t-1}` as you suggest. And I've updated the notation in the code so that the first-differenced values are represented by `Z` as agreed.

**Comment by luke-a-rogers** [comment]
There's still a difference between the forecast accuracies. It is an open question whether it's a code issue or an intrinsic transformation issue.

**Comment by luke-a-rogers** [comment]
Luke has confirmed that `N_rho` and `X_rho` forecast accuracies should not generally be equal when the time series are first-differenced by this simple example: consider `x <- 1:10`; `cor(x, x)` equals `1` but `cor(diff(x), diff(x))` is `NA`.
