### ISSUE TITLE
The new output format of a tibble that contains columns that are lists may be confusing

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pbsEDM#2]
Luke mentioned this on the phone I think but I hadn't had time to look at the code to understand it. So running the code in the vignette, we end up with 
```
pbs_calc
# A tibble: 1 x 9
      E   rho  rmse lags   observations forecasts  neighbours  distances weights
  <int> <dbl> <dbl> <name> <named list> <named li> <named lis> <named l> <named>
1     2 0.695  1.14 <int ~ <dbl [100]>  <dbl [100~ <int[,3] [~ <dbl[,10~ <dbl[,~
> 
```
The other week I came across tibbles that had columns that were lists and found them utterly confusing (isn't a tibble an extension of a data-frame which by definition is rectangular?). So we should discuss. I realise that this is what you talked about on the phone. With the previous version that outputted lists I could tease out quickly what I wanted (without looking at the documentation). Lists seem much more intuitive . 
```

**Comment by luke-a-rogers** [comment]
Thanks Andy - I've updated to output a list()
