### ISSUE TITLE
Adapt plot functions

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pbsEDM#5]
I can adapt my existing plot functions to work on output from `pbsEDM()`.

Since that output is of class `pbsEDM`, I should be able to make it so that just `plot(output)` works.

**Comment by luke-a-rogers** [comment]
Sounds good!

**Comment by andrew-edwards** [comment]
Slow day but I got my phase plots recoded - but need to double check them. Travis is happy so I think I'll stop on a positive!
Next (note to self):
- [x] adapt 3d plot
- [x] do movie loop
- [x] verify plots match my original one (be easier to do when have a movie)
- [x] do loop over E and do the final E plot in panel 6
- [ ] simplify code where possible (probably no time before needing to run simulation code)

**Comment by andrew-edwards** [comment]
`plot_observed()` only works for dim=1, and is called from `plot_time_series()`, so can be simplified right down or even removed. [Note to self to keep track of what I'm doing!].

**Comment by andrew-edwards** [comment]
`plot_observed()` no longer exists, so that last thing is done. Am not going to simplify code further (final tick box) - want to keep moving forward. Will simplify it if need to generalise code for multivariate case and non-consecutive lags. May be very tricky to make too general. Remaining ideas in my first two comments are done.
