### ISSUE TITLE
Add some more detailed explanation of the inputs and outputs for pbsEDM()

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pbsEDM#6]
I can kind of get it from the code, but it's not obvious what size certain results might be. You can do bullet points like this (I think they worked okay):
https://github.com/andrew-edwards/sizeSpectra/blob/master/R/fitting.R#L27
Big thanks if you get a chance.

To be clearer - `xt_forecast` is a vector with same length as `xt_observed` when I do an example, but is it always a vector? Looks like it is from the code. But can the input `nt` have multiple variables (e.g. predator and prey)?

**Comment by andrew-edwards** [comment]
And I see 
```
			nt_results = NULL,
			nt_observed = NULL,
			nt_forecast = NULL,
```
in the save part of `pbsEDM()` - any reason we can't save the input `nt` values (if they're non-first-difference values)? I'm wanting to recreate my six-panel plot, for which two panels are the original non-differenced data. (And I'm trying to create the plot from the `pbsEDM()` output.

Update - I'll do this. Then will have example with just input values Nt and `pbsEDM()` takes care of the first-differencing and saves the original Nt values.

**Comment by andrew-edwards** [comment]
@luke-a-rogers  - you're assuming that we always want to first-difference, yes? (And so you either input such values or tell `pbsEDM()` to do it). Authors always seem to do it but say it doesn't really matter - we may as well just do it.

**Comment by luke-a-rogers** [comment]
> I can kind of get it from the code, but it's not obvious what size certain results might be. You can do bullet points like this (I think they worked okay):
> https://github.com/andrew-edwards/sizeSpectra/blob/master/R/fitting.R#L27
> Big thanks if you get a chance.
> 
> To be clearer - `xt_forecast` is a vector with same length as `xt_observed` when I do an example, but is it always a vector? Looks like it is from the code. But can the input `nt` have multiple variables (e.g. predator and prey)?

Hi Andy,

I've updated the documentation to clarify:

  * `nt` can have multiple variables (always unlagged)
  *  How argument `lags` is used to specify the observed and the lags (description)
  * `xt_observed` and `xt_forecast` have `length = nrow(nt)` and are always vectors

Let me know if that answers your question. I'll have a look at `nt_observed` etc. now.

Luke

**Comment by luke-a-rogers** [comment]
> And I see
> 
> ```
> 			nt_results = NULL,
> 			nt_observed = NULL,
> 			nt_forecast = NULL,
> ```
> 
> in the save part of `pbsEDM()` - any reason we can't save the input `nt` values (if they're non-first-difference values)? I'm wanting to recreate my six-panel plot, for which two panels are the original non-differenced data. (And I'm trying to create the plot from the `pbsEDM()` output.
> 
> Update - I'll do this. Then will have example with just input values Nt and `pbsEDM()` takes care of the first-differencing and saves the original Nt values.

Hi Andy,

I had a look at this. I've added the non-first-differenced `nt_observed` to the output for both `pbsEDM()` and `pbsSMAP()`. Does that solve the current issue?

The `nt_results` depend on untransforming `nt_forecast` from `xt_forecast`, which will take a little thought. Let me know if this becomes a priority.

Cheers,
Luke

**Comment by luke-a-rogers** [comment]
> @luke-a-rogers - you're assuming that we always want to first-difference, yes? (And so you either input such values or tell `pbsEDM()` to do it). Authors always seem to do it but say it doesn't really matter - we may as well just do it.

Hi Andy,

Yes - I'm assuming the `nt` data come in raw (not differenced, not lagged, etc), and then I give the user the option to first-difference with the `first_difference` argument. You're right that the user could do the differencing outside the function before hand. I agree best to include the option.

Luke

**Comment by andrew-edwards** [comment]
Thanks. `nt_results` should be doable at some point, but not a priority. 

Regarding first differencing, I meant that we assume it always has to be done (whether beforehand or in the function). I think we are because if `first_difference = FALSE` then `xt` retains the `nt` values, which ..... aha..... I'd interpreted to mean that you consider the input values already lagged. Maybe you're thinking you can do the analyses on the unlagged values.
I think I'm trying to be consistent in N(t) being the raw non-first-differenced values, and X(t) being the first -differenced values, but I see that in the code you have to pick one or the other, so used xt. Maybe just a bit more explanation is needed at the top of the function. 

I want to be able to plot the raw N(t) values if they exist, like in my six panel plots. If the input `nt` is already first differenced (`first_difference = TRUE`) then I wouldn't have the N(t) values to plot (but could back calculate if necessary).

**Comment by luke-a-rogers** [comment]
> Thanks. `nt_results` should be doable at some point, but not a priority.
> 
> Regarding first differencing, I meant that we assume it always has to be done (whether beforehand or in the function). I think we are because if `first_difference = FALSE` then `xt` retains the `nt` values, which ..... aha..... I'd interpreted to mean that you consider the input values already lagged. Maybe you're thinking you can do the analyses on the unlagged values.
> I think I'm trying to be consistent in N(t) being the raw non-first-differenced values, and X(t) being the first -differenced values, but I see that in the code you have to pick one or the other, so used xt. Maybe just a bit more explanation is needed at the top of the function.
> 
> I want to be able to plot the raw N(t) values if they exist, like in my six panel plots. If the input `nt` is already first differenced (`first_difference = TRUE`) then I wouldn't have the N(t) values to plot (but could back calculate if necessary).

Hi Andy,

Ahhh, I think I understand. I use `nt` for the input values (usually raw but user defined), and `xt` to emphasize data that have (optionally) been transformed inside the function. They will be identical for the null transformation (`first_difference = FALSE` & `centre_and_scale = FALSE`), but informatively different for all other transformations. I leave it up to the user whether to first difference at all, and use the `xt` notation only to indicate that some transformation _may_ have taken place.

I agree it would be useful to add this description. I'll add it to my list of TODOs.

Luke

**Comment by andrew-edwards** [comment]
Thanks. Can I change the output to be `Nt_observed` if it's non-differenced data (and NULL if already differenced). Then that's consistent with my thinking (and the math notation), and clarifies the difference to your code. Here's the six-panel figure (currently in the vignette but using my old code):
![image](https://user-images.githubusercontent.com/6977190/84443343-45d24700-abf4-11ea-82bf-69745d998911.png)

Final panel would be different - results for different values of E I think.

**Comment by luke-a-rogers** [comment]
See updates and discussion of notation #8.
